name: Build and Deploy

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy with Docker
        run: |
          docker run --rm --privileged -v /var/run/docker.sock:/var/run/docker.sock docker:20.10 sh -c "docker-compose up -d --build"

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: 'Build and deployment successful!'
