name: Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Docker Compose
        run: |
          sudo apt-get update
          sudo apt-get install -y docker-ce docker-ce-cli containerd.io
          docker-compose --version

      - name: Build and deploy with Docker
        run: |
          mkdir -p ~/.docker
          echo '{"auths":{},"HttpHeaders":{"User-Agent":"Docker-Client/20.10.7 (linux)"}}' > ~/.docker/config.json
          docker-compose up -d --build

      - name: Send Telegram notification
        uses: appleboy/telegram-action@v0.1.1
        with:
          to: ${{ secrets.TELEGRAM_CHAT_ID }}
          token: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          message: 'Build and deployment successful!'
